// MEGA65 HyperVisor


// TRAP Writing triggers hypervisor trap $00
char * const HTRAP00 = (char*) 0xd640;
// TRAP Writing triggers hypervisor trap $01
char * const HTRAP01 = (char*) 0xd641;
// TRAP Writing triggers hypervisor trap $02
char * const HTRAP02 = (char*) 0xd642;
// TRAP Writing triggers hypervisor trap $03
char * const HTRAP03 = (char*) 0xd643;
// TRAP Writing triggers hypervisor trap $04
char * const HTRAP04 = (char*) 0xd644;
// TRAP Writing triggers hypervisor trap $05
char * const HTRAP05 = (char*) 0xd645;
// TRAP Writing triggers hypervisor trap $06
char * const HTRAP06 = (char*) 0xd646;
// TRAP Writing triggers hypervisor trap $07
char * const HTRAP07 = (char*) 0xd647;
// TRAP Writing triggers hypervisor trap $08
char * const HTRAP08 = (char*) 0xd648;
// TRAP Writing triggers hypervisor trap $09
char * const HTRAP09 = (char*) 0xd649;
// TRAP Writing triggers hypervisor trap $0a
char * const HTRAP0A = (char*) 0xd64a;
// TRAP Writing triggers hypervisor trap $0b
char * const HTRAP0B = (char*) 0xd64b;
// TRAP Writing triggers hypervisor trap $0c
char * const HTRAP0C = (char*) 0xd64c;
// TRAP Writing triggers hypervisor trap $0d
char * const HTRAP0D = (char*) 0xd64d;
// TRAP Writing triggers hypervisor trap $0e
char * const HTRAP0E = (char*) 0xd64e;
// TRAP Writing triggers hypervisor trap $0f
char * const HTRAP0F = (char*) 0xd64f;

// TRAP Writing triggers hypervisor trap $10
char * const HTRAP10 = (char*) 0xd650;
// TRAP Writing triggers hypervisor trap $11
char * const HTRAP11 = (char*) 0xd651;
// TRAP Writing triggers hypervisor trap $12
char * const HTRAP12 = (char*) 0xd652;
// TRAP Writing triggers hypervisor trap $13
char * const HTRAP13 = (char*) 0xd653;
// TRAP Writing triggers hypervisor trap $14
char * const HTRAP14 = (char*) 0xd654;
// TRAP Writing triggers hypervisor trap $15
char * const HTRAP15 = (char*) 0xd655;
// TRAP Writing triggers hypervisor trap $16
char * const HTRAP16 = (char*) 0xd656;
// TRAP Writing triggers hypervisor trap $17
char * const HTRAP17 = (char*) 0xd657;
// TRAP Writing triggers hypervisor trap $18
char * const HTRAP18 = (char*) 0xd658;
// TRAP Writing triggers hypervisor trap $19
char * const HTRAP19 = (char*) 0xd659;
// TRAP Writing triggers hypervisor trap $1a
char * const HTRAP1A = (char*) 0xd65a;
// TRAP Writing triggers hypervisor trap $1b
char * const HTRAP1B = (char*) 0xd65b;
// TRAP Writing triggers hypervisor trap $1c
char * const HTRAP1C = (char*) 0xd65c;
// TRAP Writing triggers hypervisor trap $1d
char * const HTRAP1D = (char*) 0xd65d;
// TRAP Writing triggers hypervisor trap $1e
char * const HTRAP1E = (char*) 0xd65e;
// TRAP Writing triggers hypervisor trap $1f
char * const HTRAP1F = (char*) 0xd65f;

// TRAP Writing triggers hypervisor trap $20
char * const HTRAP20 = (char*) 0xd660;
// TRAP Writing triggers hypervisor trap $21
char * const HTRAP21 = (char*) 0xd661;
// TRAP Writing triggers hypervisor trap $22
char * const HTRAP22 = (char*) 0xd662;
// TRAP Writing triggers hypervisor trap $23
char * const HTRAP23 = (char*) 0xd663;
// TRAP Writing triggers hypervisor trap $24
char * const HTRAP24 = (char*) 0xd664;
// TRAP Writing triggers hypervisor trap $25
char * const HTRAP25 = (char*) 0xd665;
// TRAP Writing triggers hypervisor trap $26
char * const HTRAP26 = (char*) 0xd666;
// TRAP Writing triggers hypervisor trap $27
char * const HTRAP27 = (char*) 0xd667;
// TRAP Writing triggers hypervisor trap $28
char * const HTRAP28 = (char*) 0xd668;
// TRAP Writing triggers hypervisor trap $29
char * const HTRAP29 = (char*) 0xd669;
// TRAP Writing triggers hypervisor trap $2a
char * const HTRAP2A = (char*) 0xd66a;
// TRAP Writing triggers hypervisor trap $2b
char * const HTRAP2B = (char*) 0xd66b;
// TRAP Writing triggers hypervisor trap $2c
char * const HTRAP2C = (char*) 0xd66c;
// TRAP Writing triggers hypervisor trap $2d
char * const HTRAP2D = (char*) 0xd66d;
// TRAP Writing triggers hypervisor trap $2e
char * const HTRAP2E = (char*) 0xd66e;
// TRAP Writing triggers hypervisor trap $2f
char * const HTRAP2F = (char*) 0xd66f;

// TRAP Writing triggers hypervisor trap $30
char * const HTRAP30 = (char*) 0xd670;
// TRAP Writing triggers hypervisor trap $31
char * const HTRAP31 = (char*) 0xd671;
// TRAP Writing triggers hypervisor trap $32
char * const HTRAP32 = (char*) 0xd672;
// TRAP Writing triggers hypervisor trap $33
char * const HTRAP33 = (char*) 0xd673;
// TRAP Writing triggers hypervisor trap $34
char * const HTRAP34 = (char*) 0xd674;
// TRAP Writing triggers hypervisor trap $35
char * const HTRAP35 = (char*) 0xd675;
// TRAP Writing triggers hypervisor trap $36
char * const HTRAP36 = (char*) 0xd676;
// TRAP Writing triggers hypervisor trap $37
char * const HTRAP37 = (char*) 0xd677;
// TRAP Writing triggers hypervisor trap $38
char * const HTRAP38 = (char*) 0xd678;
// TRAP Writing triggers hypervisor trap $39
char * const HTRAP39 = (char*) 0xd679;
// TRAP Writing triggers hypervisor trap $3a
char * const HTRAP3A = (char*) 0xd67a;
// TRAP Writing triggers hypervisor trap $3b
char * const HTRAP3B = (char*) 0xd67b;
// TRAP Writing triggers hypervisor trap $3c
char * const HTRAP3C = (char*) 0xd67c;
// TRAP Writing triggers hypervisor trap $3d
char * const HTRAP3D = (char*) 0xd67d;
// TRAP Writing triggers hypervisor trap $3e
char * const HTRAP3E = (char*) 0xd67e;
// TRAP Writing triggers hypervisor trap $3f
char * const HTRAP3F = (char*) 0xd67f;